version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=kunafa_2_db
      - POSTGRES_USER=kunafa_user
      - POSTGRES_PASSWORD=kunafa_password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: 
      - "5432:5432"
  web:
    build: .
    command: python manage.py migrate --noinput
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_DB=kunafa_2_db
      - POSTGRES_USER=kunafa_user
      - POSTGRES_PASSWORD=kunafa_password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db